FPS = 60

VIRTUAL_WIDTH = 320
VIRTUAL_HEIGHT = 240
VIRTUAL_TILE = 16

SCREEN_SCALE = 4

screen_width = VIRTUAL_WIDTH * SCREEN_SCALE
screen_height = VIRTUAL_HEIGHT * SCREEN_SCALE

INTERACT_RANGE = VIRTUAL_TILE * 2

EMP_RANGE = VIRTUAL_TILE * 5
EMP_TIME = 3